import { Link } from 'wouter';

export function RouteEconomicsDocs() {
  return <>
    <section id="near-zec" className="docs-section">
      <span className="docs-section-num">ROUTE REFERENCE</span>
      <h2>NEAR routing is not Zcash shielding.</h2>
      <p>DarkSwap offers two separate provider-backed routes, not a combined NEAR → ZEC → Solana loop. The existing private route uses a partner provider. Privacy swap uses NEAR Intents 1Click with <code>confidentiality: basic</code>. Guest orders do not earn points. Eligible orders can be considered for optional points only when an enrolled account explicitly opts in before creation.</p>
      <p>For Privacy swap, you specify the Solana input, destination asset, recipient, and Solana refund address. DarkSwap requests a dry, exact-input quote, then asks for deposit instructions only after you confirm. You send the deposit yourself. The provider coordinates execution and destination settlement; DarkSwap displays its reported status, rather than signing or broadcasting your transfer. A quote is an estimate, not proof of settlement.</p>
      <p>“Basic” requests the provider’s confidential processing for an origin-chain to destination-chain swap, on both the dry preview and deposit order. NEAR’s May 27, 2026 explanation describes encryption and restricted visibility in a private shard with independent, permissioned validators, rather than client-side proof generation. This gives swap processing a restricted environment within the provider’s trust boundary; it does not put your funds into a Zcash shielded pool, whose shielding uses zero-knowledge proofs.</p>
      <p>Your Solana deposit is public, destination-chain transfers may be public, and amounts, timing, provider records, or other data may still associate activity. No anonymity or unlinkability guarantee applies. The absence of a wallet connection does not establish privacy. The live Privacy swap route does not expose advanced mode or confidential wallet balances. Confidential balances are proposed for the separate Dark Pool on NEAR Confidential Intents, in development and not available to use; see <Link href="/docs/dark-pool">the dark pool on NEAR</Link>. Read <Link href="/docs/confidential-routing" data-testid="link-route-economics-confidential-routing">Confidential routing and ZK shielding</Link> for mechanisms, sources, and current support limits.</p>
      <div className="docs-capability-scroll" role="region" aria-label="Route capability comparison" tabIndex={0}>
        <table className="docs-capability-table">
          <caption>DarkSwap capabilities — checked September 28, 2026</caption>
          <thead><tr><th scope="col">Capability</th><th scope="col">Existing private route</th><th scope="col">Privacy swap</th></tr></thead>
          <tbody>
            <tr><th scope="row">Provider</th><td>Partner provider</td><td>NEAR Intents 1Click</td></tr>
            <tr><th scope="row">Funding</th><td>Manual Solana deposit after quote and order review</td><td>Manual Solana deposit after dry quote and order review</td></tr>
            <tr><th scope="row">Destinations</th><td>Provider catalog, subject to an accepted live quote</td><td>App permits Solana, NEAR, Ethereum, Arbitrum, Base, Optimism, Polygon, and BNB Chain; each asset still needs a quote</td></tr>
            <tr><th scope="row">Native ZEC</th><td>Read-only quote accepted; order instructions and settlement remain unverified.</td><td>Not enabled: native Zcash is outside the app’s chain allowlist; the live ZEC search returned no assets</td></tr>
            <tr><th scope="row">Zcash shielding</th><td>No shielded transfer verified by this review</td><td>Not implemented; confidential handling is a different mechanism</td></tr>
             <tr><th scope="row">Customer rewards</th><td>Optional email account points for eligible, explicitly linked new orders; no yield or cash payout</td><td>Optional email account points for eligible, explicitly linked new orders; no yield or cash payout</td></tr>
          </tbody>
        </table>
      </div>
      <h3>Native ZEC and token representations are different.</h3>
      <p>Native ZEC lives on the Zcash network. A token named ZEC on Solana or BNB Chain, or renZEC on Ethereum, is a separate representation—not native Zcash and not evidence of shielding. Check the network and exact asset identity; backing, redemption, liquidity, and bridge risks must be assessed separately. A matching ticker is not enough.</p>
      <p>The original route’s live catalog listed native ZEC, ZEC representations on Solana and BNB Chain, and renZEC on Ethereum. On September 28, 2026, a read-only development check of <strong>1 SOL to native ZEC</strong> returned eight accepted quotes. The earlier minimum-verification failure came from the provider omitting its optional input USD field. DarkSwap now checks a freshly requested USD price for the exact source token when that field is absent; it still rejects unverifiable or below-$3 inputs. The observed input valuation was $118.58, not a promised current price. Native ZEC still requires valid order instructions, and settlement has not been verified.</p>
      <div className="docs-caution"><strong>Verification limit:</strong> This review checked catalogs and a quote only. No order was created, no funds were sent, and no completed ZEC settlement or shielded transfer was demonstrated. The minimum-value blocker was not bypassed.</div>
      <p>NEAR’s broader provider documentation lists Zcash with <strong>transparent addresses only</strong> (t1/t3), not shielded addresses. That provider-level support is not enabled in DarkSwap’s Privacy swap route. Transparent Zcash transfers do not provide Zcash shielding.</p>
      <p>Provider sources: <a href="https://docs.near-intents.org/resources/chain-support" target="_blank" rel="noopener noreferrer">chain and address support</a> and <a href="https://docs.near-intents.org/integration/distribution-channels/1click-api/quickstart/confidential-swaps" target="_blank" rel="noopener noreferrer">confidential swap integration</a>. Catalogs, quotes, and provider policies can change.</p>
    </section>
    <section id="fees-rewards" className="docs-section">
      <span className="docs-section-num">FEES &amp; INCENTIVES</span>
      <h2>Swap costs are not customer earnings.</h2>
      <ul className="docs-checklist">
        <li><strong>Provider and network costs:</strong> The quote can reflect provider charges, execution costs, withdrawal costs, price impact, and liquidity conditions. Sending from your wallet can also require a network fee. A possible refund can carry a fee. The $3 input minimum is not a fee, and the 1% slippage tolerance is not a fixed charge.</li>
        {/* Fee figures and the payout address below mirror NEAR_PARTNER_FEE_BPS and NEAR_PARTNER_PAYOUT_ADDRESS on the API server; artifacts/api-server/src/routes/near-partner-fee-docs.test.ts fails if they drift. */}
        <li><strong>DarkSwap revenue:</strong> Since October 4, 2026, Privacy swap requests set <code>appFees</code> with a <strong>0.40% partner fee</strong>, charged from the asset you send and already reflected in the quoted output. Under NEAR Intents' published partner schedule that fee is split 50/50: 0.20% to DarkSwap (paid on NEAR to <code>darkswapapp.near</code>, visible in every quote request) and 0.20% to 1Click. Collected revenue is not proof of profit.</li>
         <li><strong>Optional account points:</strong> An eligible completed new order can add non-cash points only if you enroll and opt in on that order before creating it. Guest, earlier, and unlinked orders are not credited retroactively. No cashback, token payout, staking yield, or circular ZEC rewards loop is offered.</li>
      </ul>
      <p>NEAR’s published fee schedule distinguishes protocol fees, 1Click platform fees, optional integrator fees, and withdrawal costs. At review time, it listed a 0.0001% protocol fee and, for API-key requests without app fees, normally a 0.20% platform fee, reduced to 0.01% for qualifying stablecoin or same-asset multichain routes. DarkSwap’s 0.40% partner fee comes on top of those components and is split with the provider—DarkSwap does not keep the whole fee. These are provider-published components, <strong>not a verified all-in DarkSwap price</strong>; account-specific terms and actual quotes govern.</p>
       <h3>Optional email rewards and privacy</h3>
       <p>Using <Link href="/rewards">email rewards</Link> is entirely optional. Signing in with a one-time email code does not enroll you. Enrollment requires separate, explicit consent; each new order also has an off-by-default association choice at final review. If selected, the order is permanently associated with your email rewards account at creation. The account link can reduce privacy; a private route does not erase a public Solana deposit or provider records. Marketing emails are a separate choice and are not required for rewards. You may sign out without affecting guest swaps.</p>
       <p>Points are internal account ledger entries with <strong>no cash value</strong>. They are not money, cryptocurrency, a share of fees, a claim on swap proceeds, or a deposit. They cannot be sold, transferred, withdrawn, redeemed for cash, or currently exchanged for discounts. Tiers show progress only and do not guarantee any benefit. Eligibility and daily caps apply; reversals and adjustments may reduce points. View current account rules and activity on your rewards dashboard when available.</p>
        <h3>$DARK holder rewards — separate from account points</h3>
        <p>StonkFun reports $DARK graduated with a NEAR pairing and market activity. The creator fee is reported as <strong>1%, paid only in wNEAR, not DARK</strong>. <strong>Half of received $DARK creator fees funds qualifying holders in wNEAR. The other half purchases ZEC tokens on Solana for the protocol treasury in the creator wallet.</strong> Treasury holdings, separately authorized liquidity deployments, LP fee compounding, and completed holder payouts are tracked separately. This is a split of received creator-fee proceeds, not of all trading volume, router commissions or customer deposits, and it is not a guaranteed holder return. There is no buyback and burn of creator fees; buying DARK to pair in a liquidity pool is not burning it.</p>
        <p><strong>Scheduled wNEAR payouts</strong> run at 6 a.m. and 6 p.m. America/Los_Angeles time, adjusting for daylight saving. Each payout uses a fresh snapshot taken at that payout. To qualify, hold at least 100,000 $DARK in that snapshot; excluded wallets remain ineligible. Allocations are weighted by qualifying balances in that snapshot. Background monitoring cycles do not set a payout's weight and are not a countdown to an automatic ZEC payout. Payouts go direct to eligible wallets with no claim step, and past distributions do not guarantee future payouts. Earlier awards keep the rules they were paid under.</p>
        <p><strong>ZEC award, historical.</strong> A completed loyalty award distributed 1 ZEC token on Solana across 92 holders on October 5, 2026, weighted by holdings under its original checkpoint rules. Further ZEC awards require separate approval. ZEC here is a token on Solana, not native or shielded Zcash; a matching ticker does not establish backing, redemption rights or shielding. Reward mint: <code>A7bdiYdS5GjqGFtxf17ppRHtDKPkkRqbKtR27dxvQXaS</code>.</p>
        <p><strong>ZEC-DARK liquidity is separate.</strong> The ZEC-DARK pool on Meteora is protocol-funded liquidity on Solana with a 1% base trading fee (dynamic fees where applicable) and 10% of LP fees configured to compound into the pool. That 10% is a compounding setting, not a yield. The protocol reports that the $DARK creator wallet funded 99.9% of the pool’s liquidity. Reported initial funding was 2 ZEC used to buy DARK, paired with another 2 ZEC; this is protocol-reported until purchase and deposit transactions are linked. Funding is separate from position ownership and withdrawable liquidity: the creator-held position includes vested and permanently locked portions. About 2.212 ZEC was observed in the pool on October 5, 2026; that is a dated observation, not a current balance, and balance growth alone does not prove compounded fee earnings. This pool is not the Dark Pool, which is in development and not available to use.</p>
        <p>The <a href="https://rewards.darkswap.app" target="_blank" rel="noopener noreferrer" data-testid="link-docs-rewards-site">DARK Rewards console</a> is the record for holder payouts, with a <a href="https://rewards.darkswap.app/api/rewards/social-summary" target="_blank" rel="noopener noreferrer" data-testid="link-docs-rewards-summary">summary feed</a> and a <a href="https://rewards.darkswap.app/api/rewards/proof" target="_blank" rel="noopener noreferrer" data-testid="link-docs-rewards-proof">receipt export</a>. Holder payouts, DARK marketing airdrops, treasury assets and pool liquidity are reported separately; treasury balances and pool liquidity are never counted as rewards distributed. USD totals there are current-price estimates, not payout-time value or guaranteed proceeds. Holder payouts do not change non-cash account points.</p>
        <h3>Possible future swap rebate — proposed, not live</h3>
      <p>If a rebate program is pursued, fund it only from a capped share of <strong>verified, received net revenue</strong> after provider shares, operating and payout costs, refunds, and reserves—not customer deposits, swap volume, or projected commissions. If verified net revenue is zero, the rebate budget is zero.</p>
       <p>Any future cash rebate must first reconcile completed orders to verified net revenue, confirm applicable requirements, publish eligibility and payout terms, and prevent abuse. It is not part of the present points program. Linking an email to an order can undermine privacy; keep marketing consent separate and do not promise yield or guaranteed returns.</p>
       <p>Provider sources, checked September 28, 2026: <a href="https://docs.near-intents.org/resources/fees" target="_blank" rel="noopener noreferrer">fee components</a> and <a href="https://docs.near-intents.org/integration/distribution-channels/1click-api/fee-config" target="_blank" rel="noopener noreferrer">optional partner fee configuration</a>. Provider fees and any future rebate remain separate from non-cash account points.</p>
    </section>
  </>;
}