import { useEffect, useMemo, useState } from 'react';
import { Link } from 'wouter';
import { ArrowRight, BookOpen, ChevronRight, Search, ShieldAlert, X } from 'lucide-react';
import { Footer, Header } from '../components/swap-ui';
import './docs.css';

const sections = [
  { id: 'overview', label: 'Overview', group: 'START HERE', summary: 'What DarkSwap does and what is available.' },
  { id: 'availability', label: 'Beta availability', group: 'START HERE', summary: 'Two private routes open; research and public swap closed.' },
  { id: 'manual-flow', label: 'Manual deposit flow', group: 'USING THE ROUTE', summary: 'Quote, order, Solana deposit, and tracking.' },
  { id: 'route-availability', label: 'Routes, quotes & limits', group: 'USING THE ROUTE', summary: 'Supported assets and destinations vary by live quote.' },
  { id: 'tracking', label: 'Track an order', group: 'USING THE ROUTE', summary: 'Keep the order ID and check the order page.' },
  { id: 'safety', label: 'Deposit safety', group: 'BEFORE YOU SEND', summary: 'Network, amount, address, memo, and deadline checks.' },
  { id: 'privacy', label: 'Privacy limitations', group: 'BEFORE YOU SEND', summary: 'A private route is not invisibility or anonymity.' },
  { id: 'previews', label: 'Feature previews', group: 'EXPLORE PREVIEWS', summary: 'Screener Beta, Split Mixer, and Privacy Bundle are not transaction routes.' },
  { id: 'providers', label: 'Technical providers', group: 'REFERENCE', summary: 'The systems behind each route and separate beta areas.' },
  { id: 'further-reading', label: 'Independent reading', group: 'REFERENCE', summary: 'External Nullmask documentation about a different EVM privacy protocol.' },
] as const;

function jump(id: string) {
  document.getElementById(id)?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' });
  window.history.replaceState(null, '', `#${id}`);
}

export default function Docs() {
  const [search, setSearch] = useState('');
  const [mobileNav, setMobileNav] = useState(false);
  const matches = useMemo(() => sections.filter(s => `${s.label} ${s.group} ${s.summary}`.toLowerCase().includes(search.trim().toLowerCase())), [search]);
  const grouped = ['START HERE', 'USING THE ROUTE', 'BEFORE YOU SEND', 'EXPLORE PREVIEWS', 'REFERENCE'] as const;
  useEffect(() => {
    const previous = document.title;
    document.title = 'DarkSwap Docs | Private route, safety & previews';
    return () => { document.title = previous; };
  }, []);
  return <div className="app-shell docs-shell">
    <Header />
    <div className="docs-banner"><BookOpen size={17}/><span>FIELD GUIDE / PRIVATE BETA</span><span className="docs-banner-rule"/><span>Read before sending funds</span></div>
    <div className="docs-layout">
      <aside className={`docs-sidebar ${mobileNav ? 'docs-sidebar-open' : ''}`} aria-label="Documentation topics">
        <div className="docs-sidebar-top"><span>DOCUMENTATION</span><button type="button" onClick={() => setMobileNav(false)} className="docs-mobile-close" aria-label="Close topics"><X size={19}/></button></div>
        <div className="docs-search"><Search size={18} aria-hidden="true"/><input type="search" aria-label="Search documentation" placeholder="Search the guide..." value={search} onChange={e => setSearch(e.target.value)} data-testid="input-docs-search"/>{search && <button type="button" aria-label="Clear search" onClick={() => setSearch('')}><X size={16}/></button>}</div>
        {matches.length === 0 ? <p className="docs-no-results">No topics match “{search}”. Try “deposit”, “privacy”, or “order”.</p> : grouped.map(group => {
          const items = matches.filter(s => s.group === group);
          return items.length ? <div className="docs-nav-group" key={group}><span>{group}</span>{items.map(s => <a key={s.id} href={`#${s.id}`} onClick={e => { e.preventDefault(); jump(s.id); setMobileNav(false); }} data-testid={`link-docs-${s.id}`}>{s.label}<ChevronRight size={15}/></a>)}</div> : null;
        })}
        <div className="docs-sidebar-bottom"><span>READY TO CHECK A ROUTE?</span><Link href="/swap">Open private route <ArrowRight size={16}/></Link></div>
      </aside>
      <main className="docs-main">
        <button className="docs-mobile-toggle" type="button" onClick={() => setMobileNav(true)} aria-expanded={mobileNav}>Browse topics <ChevronRight size={17}/></button>
        <div className="docs-breadcrumb">DARKSWAP <ChevronRight size={13}/> DOCUMENTATION <ChevronRight size={13}/> OVERVIEW</div>
        <header className="docs-intro" id="overview"><div className="docs-intro-mark"><img src={`${import.meta.env.BASE_URL}brand/icon.png`} alt="" /></div><p className="docs-kicker">THE DARKSWAP FIELD GUIDE / 01</p><h1>Know the route.<br/><em>Then decide.</em></h1><p>This guide explains what the beta can do, what it cannot promise, and what to check before you manually send a Solana deposit.</p></header>
        <div className="docs-alert"><ShieldAlert size={22}/><div><strong>Funds do not move when you create an order.</strong><p>DarkSwap does not connect your wallet or send a transaction for you. You choose whether to deposit after reviewing the order instructions. A deposit may be irreversible.</p></div></div>
        <div className="docs-content">
          <section id="availability" className="docs-section"><span className="docs-section-num">01 / ACCESS</span><h2>What is open in beta?</h2><p>Two <strong>Solana-origin manual-deposit routes</strong> are available: the <Link href="/swap">existing private route</Link> and <Link href="/near-swap">Privacy swap</Link>. Each needs its own live quote; neither guarantees every asset or destination.</p><div className="docs-state-grid"><div><span className="docs-state-dot"/><strong>Private routes</strong><small>Two manual-deposit options; subject to live availability</small></div><div><span className="docs-state-dot closed"/><strong>Explore</strong><small>Closed beta; live token research unavailable</small></div><div><span className="docs-state-dot closed"/><strong>Public swap</strong><small>Closed beta; on-chain swaps unavailable</small></div></div><p>“Open” does not mean every pair, asset, or destination is supported. Check the quote in the route you selected. A separately available <Link href="/screener-beta">Screener Beta</Link> searches a dated catalog, not live market data.</p></section>
          <section id="manual-flow" className="docs-section"><span className="docs-section-num">02 / PROCESS</span><h2>How a manual deposit works</h2><ol className="docs-flow"><li><span>01</span><div><strong>Choose your route</strong><p>Select a Solana source asset and a destination asset, then enter an amount. Each provider returns its own supported assets and quote.</p></div></li><li><span>02</span><div><strong>Review before creating</strong><p>Check the quoted output, estimated time, limits, and destination network. Privacy swap requires both a receiving address and a Solana refund address before quoting; check them carefully. A quote can change or become unavailable.</p></div></li><li><span>03</span><div><strong>Create an order</strong><p>Confirm the details to create an order and reveal the deposit instructions. Creating the order does not transfer funds.</p></div></li><li><span>04</span><div><strong>Send manually, if you choose</strong><p>From your own Solana wallet, send exactly the instructed amount to the order’s deposit address on the specified network, with any required deposit memo. Observe the deadline.</p></div></li><li><span>05</span><div><strong>Track progress</strong><p>Keep the original route’s order ID or Privacy swap’s deposit address and track it on the corresponding order page. Completion times can vary.</p></div></li></ol></section>
          <section id="route-availability" className="docs-section"><span className="docs-section-num">03 / QUOTES</span><h2>Routes are conditional.</h2><p>Tokens, chains, amounts, fees, limits, and estimated output depend on current provider support and liquidity. A route may require information that this beta flow cannot collect; in that case it cannot be used here. Do not assume a token shown in search will have an executable quote.</p><p>If a quote fails or no route is available, change your pair or amount, or retry later. The closed-beta public swap is <strong>not</strong> an available fallback.</p></section>
          <section id="tracking" className="docs-section"><span className="docs-section-num">04 / STATUS</span><h2>Keep your order details.</h2><p>For the existing route, save the order ID and use <strong>Track an order</strong> in the header. For Privacy swap, save the Solana deposit address and bookmark its <Link href="/near-order">order page</Link>. Status updates reflect what the selected provider reports.</p><p>If the deposit appears delayed or you sent incorrect details, do not send a second payment to “fix” it. Keep the order details and sending transaction hash for support or recovery inquiries. Recovery is not guaranteed.</p><Link className="docs-inline-link" href="/near-swap">Check a Privacy swap quote <ArrowRight size={17}/></Link></section>
          <section id="safety" className="docs-section"><span className="docs-section-num">05 / CHECKLIST</span><h2>Before you send anything.</h2><ul className="docs-checklist"><li>Verify the deposit address against the active order page, not a screenshot or message.</li><li>Send on <strong>Solana only</strong> for a Solana-origin order; verify the asset and exact amount.</li><li>Include a deposit memo if the order shows one. Never guess or reuse instructions from another order.</li><li>Check the receiving address, selected destination network, quote details, and deposit deadline.</li><li>Consider a small amount you can afford to have delayed or lost. Network and provider failures are possible.</li></ul><div className="docs-caution">On-chain transfers generally cannot be reversed. A wrong network, address, asset, amount, or missing memo can lead to loss or difficult recovery.</div></section>
          <section id="privacy" className="docs-section"><span className="docs-section-num">06 / LIMITATIONS</span><h2>Privacy is not invisibility.</h2><p>DarkSwap does not require a wallet connection for its manual-deposit routes. Privacy swap requests <strong>“basic” confidential handling</strong>, distinct from the existing private route. This does <strong>not guarantee anonymity</strong> or mean the originating transfer disappears.</p><p>Solana deposits remain visible on-chain. Deposit addresses, amounts, timing, destination-chain activity, provider records, exchange compliance processes, and other external data may allow transactions to be associated. The precise privacy properties vary by route and provider. DarkSwap does not promise untraceability or risk-free execution.</p></section>
          <section id="previews" className="docs-section"><span className="docs-section-num">07 / PLANNING & RESEARCH</span><h2>What can I explore?</h2><p>These pages let you inspect ideas without creating a quote, order, payment, or funding transaction. They do not indicate that a provider supports a planned route.</p><div className="docs-preview-list"><Link href="/screener-beta"><strong>Screener Beta</strong><span>Search a dated, provider-reported Solana xStock and PreStock catalog; entries and backing are not independently verified.</span><ArrowRight size={19} aria-hidden="true"/></Link><Link href="/split-mixer-preview"><strong>Split Mixer for Solana</strong><span>Draft recipient allocations and intended legs manually or with CSV. This preview does not pool or mix funds, hide on-chain links, or connect to a provider.</span><ArrowRight size={19} aria-hidden="true"/></Link><Link href="/privacy-bundle-preview"><strong>Privacy Bundle for Launchers</strong><span>Choose a 1–12 hour planning horizon and create a conceptual brief. It does not schedule or randomize transfers, and clean wallets do not guarantee privacy.</span><ArrowRight size={19} aria-hidden="true"/></Link></div></section>
          <section id="providers" className="docs-section"><span className="docs-section-num">08 / TECHNICAL REFERENCE</span><h2>Who powers the routes?</h2><p>The <Link href="/swap">existing private route</Link> uses <strong>Houdini / HoudiniSwap</strong> for discovery, quotes, orders, and status. <Link href="/near-swap">Privacy swap</Link> separately uses the <strong>NEAR Intents 1Click API</strong> with Confidential Intents “basic” mode for dry quotes, manual-deposit instructions, and order tracking. Both depend on live provider availability. DarkSwap never broadcasts your deposit transaction.</p><p>Explore and the OKX-powered public same-chain swap remain closed beta. They should not be treated as alternative execution routes today. Provider availability, terms, fees, support, and operational conditions can change independently of this guide.</p><div className="docs-end"><img src={`${import.meta.env.BASE_URL}brand/shield.png`} alt=""/><div><strong>Review the live order, not just this guide.</strong><p>Documentation explains the flow. The active quote and order instructions govern the details of a specific transfer.</p></div></div></section>
          <section id="further-reading" className="docs-section"><span className="docs-section-num">09 / EXTERNAL READING</span><h2>Learn about other approaches.</h2><p>Nullmask publishes documentation about its own zero-knowledge privacy protocol for EVM chains. It is an <strong>independent project</strong>, not DarkSwap’s provider or an integration here. Its shielding model and privacy claims do not apply to DarkSwap’s Solana-origin manual-deposit route.</p><div className="docs-resources"><a href="https://docs.nullmask.io/introduction/introduction" target="_blank" rel="noopener noreferrer"><strong>What is Nullmask?</strong><span>Read the independent project’s introduction (external site).</span><ArrowRight size={19} aria-hidden="true"/></a><a href="https://docs.nullmask.io/introduction/how-it-works" target="_blank" rel="noopener noreferrer"><strong>How Nullmask works</strong><span>Compare the concepts behind its EVM-based protocol (external site).</span><ArrowRight size={19} aria-hidden="true"/></a></div><p className="docs-resource-note">Links are for general learning, not an endorsement or a description of DarkSwap’s implementation. Always judge the active DarkSwap quote and order instructions on their own terms.</p></section>
        </div>
        <div className="docs-next"><span>WHEN YOU ARE READY</span><strong>Take the route one step at a time.</strong><Link href="/swap">Check a live quote <ArrowRight size={18}/></Link></div>
      </main>
      <aside className="docs-toc" aria-label="On this page"><span>ON THIS PAGE</span>{sections.map(s => <a href={`#${s.id}`} key={s.id} onClick={e => { e.preventDefault(); jump(s.id); }}>{s.label}</a>)}<div className="docs-toc-note">Only send funds after checking the active order instructions.</div></aside>
    </div>
    <Footer/>
  </div>;
}