// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/darkswap-beta/Current.tsx": () => import("../components/mockups/darkswap-beta/Current.tsx"),
  "./components/mockups/darkswap-beta/Launch.tsx": () => import("../components/mockups/darkswap-beta/Launch.tsx"),
  "./components/mockups/darkswap-nearfi/CurrentExchange.tsx": () => import("../components/mockups/darkswap-nearfi/CurrentExchange.tsx"),
  "./components/mockups/darkswap-nearfi/CurrentTracking.tsx": () => import("../components/mockups/darkswap-nearfi/CurrentTracking.tsx"),
  "./components/mockups/darkswap-nearfi/Exchange.tsx": () => import("../components/mockups/darkswap-nearfi/Exchange.tsx"),
  "./components/mockups/darkswap-nearfi/Tracking.tsx": () => import("../components/mockups/darkswap-nearfi/Tracking.tsx"),
  "./components/mockups/maximum-privacy/BoldIntent.tsx": () => import("../components/mockups/maximum-privacy/BoldIntent.tsx"),
  "./components/mockups/maximum-privacy/Current.tsx": () => import("../components/mockups/maximum-privacy/Current.tsx"),
  "./components/mockups/maximum-privacy/QuietControl.tsx": () => import("../components/mockups/maximum-privacy/QuietControl.tsx")
};
