// Converts snarkjs verification_key.json into the Rust constant that
// groth16-solana expects.
//   G1 point: x || y, each 32 bytes big-endian.
//   G2 point: x.c1 || x.c0 || y.c1 || y.c0, each 32 bytes big-endian
//             (snarkjs stores [c0, c1]; the EVM and Solana want c1 first).
import fs from "node:fs";

const [, , inPath, outPath] = process.argv;
if (!inPath || !outPath) {
  console.error("usage: node vk-to-rust.mjs <verification_key.json> <out.rs>");
  process.exit(1);
}
const vk = JSON.parse(fs.readFileSync(inPath, "utf8"));

const be32 = (dec) => {
  const hex = BigInt(dec).toString(16).padStart(64, "0");
  return hex.match(/../g).map((b) => parseInt(b, 16));
};
const g1 = (p) => [...be32(p[0]), ...be32(p[1])];
const g2 = (p) => [...be32(p[0][1]), ...be32(p[0][0]), ...be32(p[1][1]), ...be32(p[1][0])];
const rows = (bytes, indent) => {
  const out = [];
  for (let i = 0; i < bytes.length; i += 16)
    out.push(indent + bytes.slice(i, i + 16).join(", ") + ",");
  return out.join("\n");
};

let s = `// GENERATED by scripts/vk-to-rust.mjs from ${inPath.split("/").pop()}. Do not edit.
// These are DEV-ONLY keys until the setup ceremony replaces them.
use groth16_solana::groth16::Groth16Verifyingkey;

pub const NR_PUBLIC_INPUTS: usize = ${vk.nPublic};

pub const VERIFYING_KEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: ${vk.IC.length},
    vk_alpha_g1: [
${rows(g1(vk.vk_alpha_1), "        ")}
    ],
    vk_beta_g2: [
${rows(g2(vk.vk_beta_2), "        ")}
    ],
    vk_gamme_g2: [
${rows(g2(vk.vk_gamma_2), "        ")}
    ],
    vk_delta_g2: [
${rows(g2(vk.vk_delta_2), "        ")}
    ],
    vk_ic: &[
${vk.IC.map((p) => `        [\n${rows(g1(p), "            ")}\n        ],`).join("\n")}
    ],
};
`;
fs.writeFileSync(outPath, s);
console.log(`wrote ${outPath} (${vk.IC.length - 1} public inputs)`);
